// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.commands;


import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2881.karlk.subsystems.LiftSubsystem;

/**
 *
 */
public class AutonomousRobotPrep extends CommandGroup {

    public AutonomousRobotPrep() {

        addSequential(new WaitForPressure());
        addSequential(new SetClaw(LiftSubsystem.ClawState.CLOSED));
        addSequential(new WaitUntilNavXCalibrated());
        addSequential(new ArmAssistDeploy(true));
        addSequential(new CalibrateArmEncoder(true));
    }

    @Override
    protected void initialize() {
        System.out.println("AutonomousRobotPrep has started");
    }

    @Override
    protected void end() {
        System.out.println("AutonomousRobotPrep has ended");
    }
}
