// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2881.karlk.Robot;
import org.usfirst.frc2881.karlk.subsystems.LiftSubsystem;

/**
 *
 */
public class AutonomousWatchDog extends Command {
    private final Command autonomous;

    public AutonomousWatchDog(Command autonomous) {
        this.autonomous = autonomous;
    }

    @Override
    protected void execute() {
        if (Robot.driveSubsystem.abortAuto()) {
            autonomous.cancel();
        }
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return !autonomous.isRunning();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveSubsystem.tankDrive(0, 0, false);
        Robot.liftSubsystem.setArmMotorSpeed(0);
        Robot.climbingSubsystem.climb(0);
        Robot.intakeSubsystem.rollers(0);
        Robot.liftSubsystem.setClaw(LiftSubsystem.ClawState.OPEN);
        new RumbleNo(Robot.oi.manipulator).start();
        Robot.log("Autonomous Terminated");
    }

}
