// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc2881.karlk.subsystems.DriveSubsystem;

/**
 *
 */
public class AutonomousCommand extends CommandGroup {

    public AutonomousCommand() {
        addSequential(new RobotPrep());
        addSequential(new AutoSwitchCommand(DriveSubsystem.StartingLocation.LEFT, DriveSubsystem.SwitchPosition.FRONT));

    }

    @Override
    protected void initialize() {
        System.out.println("Autonomous command has started");
    }

    @Override
    protected void end() {
        System.out.println("Autonomous command has ended");
    }
}
