// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.InstantCommand;
import org.usfirst.frc2881.karlk.Robot;

import java.time.Instant;

import static org.usfirst.frc2881.karlk.RobotMap.driveSubsystemDropOmniPancake;

/**
 *
 */
public class DeployOmnis extends InstantCommand {
    private boolean deploy;
    public DeployOmnis(boolean deploy) {
        requires(Robot.driveSubsystem);
        this.deploy = deploy;
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        //this turns the piston to true/extended
        Robot.driveSubsystem.dropOmniPancakePiston(this.deploy);
    }

// Called repeatedly when this Command is scheduled to run
        }
