// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.subsystems;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2881.karlk.RobotMap;
import org.usfirst.frc2881.karlk.commands.Climb;

/**
 *
 */
public class ClimbingSubsystem extends Subsystem {
    private final Solenoid extender = RobotMap.climbingSubsystemExtender;
    private final SpeedController winch = RobotMap.climbingSubsystemWinch;

    @Override
    public void initDefaultCommand() {
        setDefaultCommand(new Climb());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void climb(double speed) {
        if (speed >= 0) {
            winch.set(speed);
        } else {
            // we are assuming that we cannot run the winch backward (because last year the winch was a ratchet)
            winch.stopMotor();
        }
    }

}

