// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2881.karlk.subsystems;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc2881.karlk.RobotMap;

/**
 *
 */
public class IntakeSubsystem extends Subsystem {
    private final Solenoid intakeDeploy = RobotMap.intakeSubsystemIntakeDeploy;
    private final Solenoid grasper = RobotMap.intakeSubsystemGrasper;
    private final DigitalInput intakeDetector = RobotMap.intakeSubsystemIntakeDetector;
    private final SpeedController intakeRollerLeft = RobotMap.intakeSubsystemIntakeRollerLeft;
    private final SpeedController intakeRollerRight = RobotMap.intakeSubsystemIntakeRollerRight;
    private final SpeedControllerGroup intakeRollerGroup = RobotMap.intakeSubsystemIntakeRollerGroup;

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

